# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
