# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20170902_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
