# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20170902_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='LoginLog',
        ),
    ]
