# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20170902_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='idd',
            field=models.IntegerField(default=0),
        ),
    ]
